
import streamlit as st
import pandas as pd
import plotly.express as px
import requests
from io import StringIO
from datetime import datetime

# =========================================================
# APP CONFIG
# =========================================================

st.set_page_config(
    page_title="What Schemas Should I Care About?",
    page_icon="🎯",
    layout="wide"
)

GITHUB_API_URL = "https://api.github.com/repos/schemaorg/schemaorg/contents/data/public_stats/google?ref=main"
RAW_BASE_URL = "https://raw.githubusercontent.com/schemaorg/schemaorg/main/data/public_stats/google/"
FALLBACK_FILE = "2026_05.csv"

BUCKET_ORDER = {
    "< 1K": 1,
    "1K - 10K": 2,
    "10K - 100K": 3,
    "100K - 1M": 4,
    "> 1M": 5,
}

BUCKET_MIDPOINT = {
    "< 1K": 500,
    "1K - 10K": 5500,
    "10K - 100K": 55000,
    "100K - 1M": 550000,
    "> 1M": 1500000,
}

# =========================================================
# EDITABLE GOOGLE / SEO KNOWLEDGE LAYER
# =========================================================
# Update this layer as Google documentation changes.
# The goal is not to claim ranking impact.
# The goal is to prioritize audit work by combining:
# public adoption + Google documented features + niche relevance + plugin-default bias.

SCHEMA_KNOWLEDGE = {
    "Article": {
        "google_feature": "Article",
        "google_status": "Documented rich result",
        "industries": ["Publisher", "News", "Education", "Healthcare", "SaaS"],
        "templates": ["Article page", "Blog post", "News article"],
        "value": 4,
        "bias": "High",
        "why": "Core markup for editorial and informational content. Commonly generated by CMS templates.",
        "audit": "Check headline, image, author, datePublished, dateModified, publisher, and duplication with WebPage.",
    },
    "NewsArticle": {
        "google_feature": "Article",
        "google_status": "Documented rich result",
        "industries": ["Publisher", "News"],
        "templates": ["News article"],
        "value": 4,
        "bias": "Medium",
        "why": "Relevant for news publishers and time-sensitive editorial content.",
        "audit": "Use only for real news content. Validate dates, author, publisher, and freshness.",
    },
    "BlogPosting": {
        "google_feature": "Article",
        "google_status": "Related to documented Article markup",
        "industries": ["Publisher", "Education", "Healthcare", "SaaS"],
        "templates": ["Blog post"],
        "value": 3,
        "bias": "High",
        "why": "Common in CMS-generated blog templates. Useful, but rarely a competitive advantage alone.",
        "audit": "Check whether BlogPosting, Article, and WebPage markup are duplicated or conflicting.",
    },
    "BreadcrumbList": {
        "google_feature": "Breadcrumb",
        "google_status": "Documented rich result",
        "industries": ["Ecommerce", "Marketplace", "Publisher", "News", "Local Business", "SaaS", "Education", "Healthcare", "Entertainment", "Travel"],
        "templates": ["All templates"],
        "value": 5,
        "bias": "High",
        "why": "Foundational schema for site hierarchy and SERP breadcrumb display.",
        "audit": "Audit hierarchy consistency, canonical category paths, and whether all important templates output breadcrumbs.",
    },
    "Product": {
        "google_feature": "Product snippets / Merchant listings",
        "google_status": "Documented rich result",
        "industries": ["Ecommerce", "Marketplace", "SaaS"],
        "templates": ["Product page"],
        "value": 5,
        "bias": "High",
        "why": "High-value commercial markup for product pages, but adoption is often inflated by ecommerce platforms and plugins.",
        "audit": "Check offers, price, availability, image, brand, sku/gtin, aggregateRating, Review, and Merchant Center consistency.",
    },
    "Offer": {
        "google_feature": "Product snippets / Merchant listings",
        "google_status": "Required/related property type for Product",
        "industries": ["Ecommerce", "Marketplace"],
        "templates": ["Product page"],
        "value": 5,
        "bias": "Medium",
        "why": "Critical for commercial product eligibility because price and availability usually live in Offer.",
        "audit": "Keep price, currency, availability, validFrom/priceValidUntil aligned with visible page content.",
    },
    "AggregateRating": {
        "google_feature": "Review snippets / Product snippets",
        "google_status": "Related to documented Review/Product markup",
        "industries": ["Ecommerce", "Marketplace", "Local Business", "Entertainment", "Education", "Travel"],
        "templates": ["Product page", "Review page", "Location page", "Course page"],
        "value": 4,
        "bias": "Medium",
        "why": "Can support rating visibility when ratings are genuine, visible, and policy-compliant.",
        "audit": "Avoid invisible, self-serving, or inflated ratings. Validate ratingCount/reviewCount and visible source.",
    },
    "Review": {
        "google_feature": "Review snippet",
        "google_status": "Documented rich result",
        "industries": ["Ecommerce", "Marketplace", "Local Business", "Entertainment", "Education", "Travel"],
        "templates": ["Product page", "Review page", "Location page"],
        "value": 4,
        "bias": "Medium",
        "why": "Useful where review content is a real decision factor.",
        "audit": "Ensure reviews are visible, genuine, tied to the reviewed item, and not self-serving misuse.",
    },
    "LocalBusiness": {
        "google_feature": "Local business",
        "google_status": "Documented rich result",
        "industries": ["Local Business", "Healthcare", "Travel"],
        "templates": ["Homepage", "Location page"],
        "value": 5,
        "bias": "Medium",
        "why": "Important for local entities, location pages, and business detail features.",
        "audit": "Validate NAP, openingHours, address, geo, telephone, sameAs, and location-specific page consistency.",
    },
    "Organization": {
        "google_feature": "Organization / Logo",
        "google_status": "Documented structured data feature",
        "industries": ["Ecommerce", "Marketplace", "Publisher", "News", "Local Business", "SaaS", "Education", "Healthcare", "Entertainment", "Travel"],
        "templates": ["Homepage", "About page"],
        "value": 3,
        "bias": "High",
        "why": "Good for entity clarity, but often plugin-generated and rarely the biggest missing opportunity.",
        "audit": "Check logo, legalName/name, url, sameAs, contactPoint, and whether multiple Organization nodes conflict.",
    },
    "Event": {
        "google_feature": "Event",
        "google_status": "Documented rich result",
        "industries": ["Local Business", "Education", "Entertainment", "Publisher", "Travel"],
        "templates": ["Event page"],
        "value": 5,
        "bias": "Low",
        "why": "Very actionable when event pages exist, and lower plugin-default bias makes gaps meaningful.",
        "audit": "Validate startDate, endDate, location, offers, performer/organizer, status, and freshness.",
    },
    "JobPosting": {
        "google_feature": "Job posting",
        "google_status": "Documented rich result",
        "industries": ["Marketplace", "SaaS", "Education"],
        "templates": ["Job page", "Careers page"],
        "value": 5,
        "bias": "Low",
        "why": "High-value schema for job boards and career pages.",
        "audit": "Audit hiringOrganization, jobLocation, datePosted, validThrough, employmentType, salary, and expired jobs.",
    },
    "Course": {
        "google_feature": "Course / Course list",
        "google_status": "Documented rich result",
        "industries": ["Education"],
        "templates": ["Course page", "Course listing"],
        "value": 5,
        "bias": "Low",
        "why": "High relevance for course catalogs; low adoption can indicate underused niche opportunity.",
        "audit": "Validate provider, name, description, offers, courseInstance when applicable, and visible course details.",
    },
    "Recipe": {
        "google_feature": "Recipe",
        "google_status": "Documented rich result",
        "industries": ["Publisher", "Food"],
        "templates": ["Recipe page"],
        "value": 5,
        "bias": "Medium",
        "why": "Critical for recipe publishers; irrelevant outside actual recipe content.",
        "audit": "Check ingredients, instructions, prepTime, cookTime, nutrition, image, and visible recipe steps.",
    },
    "VideoObject": {
        "google_feature": "Video",
        "google_status": "Documented rich result",
        "industries": ["Publisher", "News", "Education", "Entertainment", "SaaS", "Ecommerce"],
        "templates": ["Video page", "Article page", "Product page", "Course page"],
        "value": 4,
        "bias": "Medium",
        "why": "Often under-audited despite strong rich-result relevance when video is central to the page.",
        "audit": "Validate thumbnailUrl, uploadDate, duration, name, description, embedUrl/contentUrl, and video sitemap alignment.",
    },
    "Movie": {
        "google_feature": "Movie carousel",
        "google_status": "Documented rich result",
        "industries": ["Entertainment"],
        "templates": ["Movie page", "Listing page"],
        "value": 4,
        "bias": "Low",
        "why": "Strong niche fit for streaming catalogs, movie databases, and entertainment listings.",
        "audit": "Validate movie entity data, images, director/actor, ratings if visible, and carousel/list eligibility.",
    },
    "Dataset": {
        "google_feature": "Dataset",
        "google_status": "Documented rich result",
        "industries": ["Education", "Publisher", "SaaS", "Healthcare"],
        "templates": ["Dataset page", "Research page"],
        "value": 3,
        "bias": "Low",
        "why": "Niche but valuable for real datasets, research assets, and public data repositories.",
        "audit": "Use only for actual datasets. Validate name, description, creator, distribution, license, and temporal/spatial coverage.",
    },
    "SoftwareApplication": {
        "google_feature": "Software app",
        "google_status": "Documented rich result",
        "industries": ["SaaS", "Marketplace"],
        "templates": ["Software product page", "App page"],
        "value": 4,
        "bias": "Low",
        "why": "Useful for app pages, SaaS product pages, tool directories, and software marketplaces.",
        "audit": "Validate operatingSystem, applicationCategory, offers, aggregateRating, and visible software details.",
    },
    "FAQPage": {
        "google_feature": "FAQ",
        "google_status": "Limited / reduced visibility",
        "industries": ["Ecommerce", "SaaS", "Education", "Healthcare", "Local Business"],
        "templates": ["FAQ page", "Support page", "Product page"],
        "value": 2,
        "bias": "High",
        "why": "Historically overused. Still valid semantically, but weak as a rich-result growth lever.",
        "audit": "Use only for visible FAQs. Do not prioritize over Product, VideoObject, Course, Event, etc. where those fit.",
    },
    "HowTo": {
        "google_feature": "How-to",
        "google_status": "Limited / reduced visibility",
        "industries": ["Publisher", "Education", "SaaS"],
        "templates": ["Guide page", "Support page"],
        "value": 2,
        "bias": "Medium",
        "why": "Use for genuine instructional pages, but treat as lower Search-display opportunity than before.",
        "audit": "Only mark up visible step-by-step content. Avoid generic articles with no clear steps.",
    },
    "Person": {
        "google_feature": "Entity understanding",
        "google_status": "Not a standalone rich result",
        "industries": ["Publisher", "News", "Education", "Healthcare"],
        "templates": ["Author page", "Bio page", "Article page"],
        "value": 3,
        "bias": "Medium",
        "why": "Important for expert/author/entity clarity but not a direct rich-result target.",
        "audit": "Use for real authors, experts, doctors, instructors, and contributors. Link to sameAs where useful.",
    },
    "TVSeries": {
        "google_feature": "Entity understanding",
        "google_status": "Not a standalone rich result",
        "industries": ["Entertainment"],
        "templates": ["Series page"],
        "value": 3,
        "bias": "Low",
        "why": "Useful for entertainment entity architecture, even if not directly a rich-result type.",
        "audit": "Use with TVSeason, TVEpisode, VideoObject, Review, and AggregateRating where the page model supports it.",
    },
    "TVSeason": {
        "google_feature": "Entity understanding",
        "google_status": "Not a standalone rich result",
        "industries": ["Entertainment"],
        "templates": ["Season page"],
        "value": 2,
        "bias": "Low",
        "why": "Useful when season pages exist; lower adoption should not disqualify it for the right template.",
        "audit": "Use only when the site has season-level entities/pages.",
    },
    "TVEpisode": {
        "google_feature": "Entity understanding",
        "google_status": "Not a standalone rich result",
        "industries": ["Entertainment"],
        "templates": ["Episode page"],
        "value": 2,
        "bias": "Low",
        "why": "Useful for episode pages, especially when paired with VideoObject.",
        "audit": "Use where episode metadata is visible and stable.",
    },
    "DiscussionForumPosting": {
        "google_feature": "Discussion forum",
        "google_status": "Documented rich result",
        "industries": ["Publisher", "SaaS", "Education"],
        "templates": ["Forum thread", "Community post"],
        "value": 4,
        "bias": "Low",
        "why": "Relevant for user-generated discussions and community content.",
        "audit": "Use for genuine forum/thread content, not normal editorial pages.",
    },
    "QAPage": {
        "google_feature": "Q&A",
        "google_status": "Documented rich result",
        "industries": ["Education", "SaaS", "Publisher"],
        "templates": ["Q&A page", "Support community"],
        "value": 4,
        "bias": "Low",
        "why": "Useful where pages have one question and multiple answers or accepted answers.",
        "audit": "Do not use for FAQ lists. Use when the page is actually Q&A.",
    },
    "ProfilePage": {
        "google_feature": "Profile page",
        "google_status": "Documented rich result",
        "industries": ["Publisher", "SaaS", "Marketplace", "Education"],
        "templates": ["Profile page", "Author page", "User page"],
        "value": 3,
        "bias": "Low",
        "why": "Useful for person or organization profile pages.",
        "audit": "Use where the page primarily focuses on a single person or organization.",
    },
    "VacationRental": {
        "google_feature": "Vacation rental",
        "google_status": "Documented rich result",
        "industries": ["Travel"],
        "templates": ["Rental listing"],
        "value": 5,
        "bias": "Low",
        "why": "High niche value for vacation rental platforms and listing pages.",
        "audit": "Validate listing details, location, images, price/availability pipeline, and policy requirements.",
    },
}

NICHE_PLAYBOOKS = {
    "Ecommerce": ["Product", "Offer", "AggregateRating", "Review", "BreadcrumbList", "Organization", "VideoObject", "FAQPage"],
    "Marketplace": ["Product", "Offer", "AggregateRating", "Review", "BreadcrumbList", "Organization", "JobPosting", "SoftwareApplication", "ProfilePage"],
    "Publisher": ["Article", "BlogPosting", "NewsArticle", "Person", "Organization", "BreadcrumbList", "VideoObject", "FAQPage", "Dataset", "DiscussionForumPosting"],
    "News": ["NewsArticle", "Article", "Person", "Organization", "BreadcrumbList", "VideoObject"],
    "Local Business": ["LocalBusiness", "Organization", "BreadcrumbList", "Review", "AggregateRating", "Event", "FAQPage"],
    "SaaS": ["SoftwareApplication", "Product", "Organization", "Article", "VideoObject", "FAQPage", "HowTo", "BreadcrumbList", "QAPage"],
    "Education": ["Course", "Article", "Person", "Organization", "VideoObject", "Dataset", "FAQPage", "Event", "QAPage", "BreadcrumbList"],
    "Healthcare": ["LocalBusiness", "Person", "Article", "Organization", "FAQPage", "Review", "Dataset", "BreadcrumbList"],
    "Entertainment": ["Movie", "VideoObject", "TVSeries", "TVSeason", "TVEpisode", "Review", "AggregateRating", "BreadcrumbList", "Event"],
    "Travel": ["VacationRental", "LocalBusiness", "Event", "Review", "AggregateRating", "BreadcrumbList", "Organization", "FAQPage"],
}

# =========================================================
# DATA LOADING
# =========================================================

def normalize_bucket(value):
    value = str(value).strip()
    replacements = {
        "0-1K": "< 1K",
        "0 - 1K": "< 1K",
        "<1K": "< 1K",
        "< 1k": "< 1K",
        "1k-10k": "1K - 10K",
        "1K-10K": "1K - 10K",
        "10K-100K": "10K - 100K",
        "100K-1M": "100K - 1M",
        "1M+": "> 1M",
        ">1M": "> 1M",
    }
    return replacements.get(value, value)


def normalize_term(value):
    value = str(value).strip()
    value = value.replace("http://schema.org/", "")
    value = value.replace("https://schema.org/", "")
    value = value.replace("schema:", "")
    value = value.split("/")[-1]
    return value.strip()


def parse_detected_schemas(text):
    if not text:
        return []
    for sep in ["\n", ";", "|", "\t"]:
        text = text.replace(sep, ",")
    return sorted(set([normalize_term(x) for x in text.split(",") if normalize_term(x)]))


@st.cache_data(ttl=3600)
def get_csv_files():
    try:
        response = requests.get(GITHUB_API_URL, timeout=20)
        if response.status_code != 200:
            return [FALLBACK_FILE]
        items = response.json()
        csv_files = sorted([item.get("name") for item in items if item.get("name", "").endswith(".csv")])
        return csv_files if csv_files else [FALLBACK_FILE]
    except Exception:
        return [FALLBACK_FILE]


@st.cache_data(ttl=3600)
def load_month(file_name):
    url = RAW_BASE_URL + file_name
    response = requests.get(url, timeout=30)
    if response.status_code != 200:
        raise RuntimeError(f"Could not download {file_name}")

    raw = pd.read_csv(StringIO(response.text))
    required_cols = ["Class", "Name", "Domain Bucket"]
    missing = [c for c in required_cols if c not in raw.columns]
    if missing:
        raise RuntimeError(f"Missing required columns: {missing}")

    df = raw.copy()
    df["month"] = file_name.replace(".csv", "")
    df["term_type"] = df["Class"].astype(str).str.strip()
    df["term"] = df["Name"].apply(normalize_term)
    df["bucket"] = df["Domain Bucket"].apply(normalize_bucket)
    df["adoption_tier"] = df["bucket"].map(BUCKET_ORDER).fillna(0).astype(int)
    df["estimated_domains_midpoint"] = df["bucket"].map(BUCKET_MIDPOINT).fillna(0).astype(int)

    return df[["month", "term_type", "term", "bucket", "adoption_tier", "estimated_domains_midpoint"]]


@st.cache_data(ttl=3600)
def load_all_data():
    files = get_csv_files()
    frames = []
    skipped = []
    for file in files:
        try:
            frames.append(load_month(file))
        except Exception as exc:
            skipped.append((file, str(exc)))

    if not frames:
        st.error("No Schema.org public usage statistics CSV could be loaded.")
        st.stop()

    return pd.concat(frames, ignore_index=True), files, skipped

# =========================================================
# SCORING
# =========================================================

def knowledge(term, key, default=None):
    return SCHEMA_KNOWLEDGE.get(term, {}).get(key, default)


def status_points(status):
    if status == "Documented rich result":
        return 35
    if status == "Documented structured data feature":
        return 25
    if status == "Related to documented Article markup":
        return 22
    if status == "Related to documented Review/Product markup":
        return 25
    if status == "Required/related property type for Product":
        return 25
    if status == "Limited / reduced visibility":
        return 8
    if status == "Not a standalone rich result":
        return 5
    return 0


def bias_penalty(bias):
    if bias == "High":
        return 15
    if bias == "Medium":
        return 8
    if bias == "Low":
        return 0
    return 4


def classify_opportunity(row):
    if row["site_status"] == "Detected":
        if row["priority_score"] >= 60:
            return "Audit quality"
        return "Monitor"

    if row["google_documented"] and row["niche_relevant"] and row["adoption_tier"] <= 3:
        return "Hidden gap"
    if row["google_documented"] and row["niche_relevant"] and row["adoption_tier"] >= 4:
        return "Core missing schema"
    if row["google_status"] == "Limited / reduced visibility":
        return "Use cautiously"
    if row["google_documented"] and not row["niche_relevant"]:
        return "Documented, weak niche fit"
    if (not row["google_documented"]) and row["niche_relevant"]:
        return "Semantic opportunity"
    if row["adoption_tier"] >= 4 and row["cms_bias"] == "High":
        return "Popular / plugin-driven"
    return "Low priority"


def priority_label(score):
    if score >= 80:
        return "Critical"
    if score >= 60:
        return "High"
    if score >= 40:
        return "Medium"
    return "Low"


def enrich(df, niche, detected_terms):
    df = df.copy()
    playbook = set(NICHE_PLAYBOOKS.get(niche, []))
    detected = set(detected_terms)

    df["google_feature"] = df["term"].apply(lambda t: knowledge(t, "google_feature", "No Google mapping"))
    df["google_status"] = df["term"].apply(lambda t: knowledge(t, "google_status", "Not mapped"))
    df["seo_value"] = df["term"].apply(lambda t: knowledge(t, "value", 1))
    df["cms_bias"] = df["term"].apply(lambda t: knowledge(t, "bias", "Unknown"))
    df["why_it_matters"] = df["term"].apply(lambda t: knowledge(t, "why", "No curated note yet. Treat as raw Schema.org adoption data."))
    df["audit_focus"] = df["term"].apply(lambda t: knowledge(t, "audit", "Validate against visible content, Google guidelines, and business relevance."))
    df["niche_relevant"] = df["term"].apply(lambda t: niche in knowledge(t, "industries", []))
    df["in_niche_playbook"] = df["term"].apply(lambda t: t in playbook)
    df["site_status"] = df["term"].apply(lambda t: "Detected" if t in detected else "Missing")

    df["google_documented"] = df["google_status"].apply(
        lambda x: (
            "Documented rich result" in x
            or "Documented structured data feature" in x
            or "Related to documented" in x
            or "Required/related" in x
        )
    )

    df["priority_score"] = (
        df["adoption_tier"] * 8
        + df["seo_value"] * 8
        + df["google_status"].apply(status_points)
        + df["niche_relevant"].astype(int) * 15
        + df["in_niche_playbook"].astype(int) * 15
        - df["cms_bias"].apply(bias_penalty)
    ).clip(lower=0, upper=100).round(0).astype(int)

    df["priority"] = df["priority_score"].apply(priority_label)
    df["recommendation_bucket"] = df.apply(classify_opportunity, axis=1)

    return df


def make_recommendation(row, niche):
    term = row["term"]
    status = row["site_status"]

    if status == "Detected":
        action = "Audit implementation quality, validation errors, duplicate nodes, required/recommended properties, and alignment with visible page content."
    elif row["recommendation_bucket"] in ["Hidden gap", "Core missing schema"]:
        action = "Prioritize implementation on the relevant template. This schema has clear niche/search relevance and is currently missing from the provided detected list."
    elif row["recommendation_bucket"] == "Semantic opportunity":
        action = "Consider implementation if the site has a real entity/template need. Do not position it as a direct rich-result lever."
    elif row["recommendation_bucket"] == "Use cautiously":
        action = "Use only when it truly matches visible page content. Avoid treating it as a high-impact rich-result tactic."
    else:
        action = "Keep as a lower-priority investigation item unless there is a strong business/template reason."

    return f"""### {term}

**Status:** {row['site_status']}  
**Priority:** {row['priority']} ({row['priority_score']}/100)  
**Opportunity bucket:** {row['recommendation_bucket']}  
**Adoption:** {row['bucket']}  
**Google feature:** {row['google_feature']}  
**Google status:** {row['google_status']}  
**Niche relevance for {niche}:** {'Yes' if row['niche_relevant'] else 'No'}  
**CMS/plugin bias:** {row['cms_bias']}

**Why it matters:**  
{row['why_it_matters']}

**Recommended action:**  
{action}

**Audit focus:**  
{row['audit_focus']}
"""


# =========================================================
# LOAD DATA
# =========================================================

all_df, csv_files, skipped_files = load_all_data()
months = sorted(all_df["month"].unique(), reverse=True)

# =========================================================
# UI
# =========================================================

st.title("🎯 What Schemas Should I Care About for My Niche?")

st.markdown(
    """
A niche-first structured data prioritization tool for SEO professionals.

Instead of asking **“which Schema.org type is most used?”**, this app asks:

> **Which schemas are worth caring about for this specific site type?**

It combines Schema.org public usage buckets with an editable Google rich-result knowledge layer, niche relevance, and CMS/plugin-default bias.
"""
)

st.info(
    "Google structured data documentation indicates eligibility for rich-result features, not guaranteed Search appearance. Use this as an audit prioritization model."
)

st.sidebar.header("1. Choose or customize the niche")

niche_mode = st.sidebar.radio(
    "Niche mode",
    ["Use preset niche", "Customize niche"],
    horizontal=False,
    key="niche_mode"
)

selected_niche = st.sidebar.selectbox(
    "Base niche / site type",
    list(NICHE_PLAYBOOKS.keys()),
    key="selected_niche"
)

base_playbook_terms = NICHE_PLAYBOOKS[selected_niche]

all_available_terms = sorted(
    set(all_df["term"].dropna().unique().tolist())
    .union(set(SCHEMA_KNOWLEDGE.keys()))
)

if niche_mode == "Customize niche":
    custom_playbook_terms = st.sidebar.multiselect(
        "Customize schema terms for this niche",
        options=all_available_terms,
        default=[term for term in base_playbook_terms if term in all_available_terms],
        key="custom_playbook_terms"
    )

    custom_niche_name = st.sidebar.text_input(
        "Custom niche name",
        value=f"Custom {selected_niche}",
        key="custom_niche_name"
    )

    active_niche = custom_niche_name
    active_playbook_terms = custom_playbook_terms

else:
    active_niche = selected_niche
    active_playbook_terms = base_playbook_terms

selected_month = st.sidebar.selectbox(
    "Schema.org usage dataset month",
    months,
    key="selected_month"
)

st.sidebar.header("2. Optional: paste schemas already detected")

detected_text = st.sidebar.text_area(
    "Detected schemas",
    value="",
    placeholder="Example: Organization, WebSite, BreadcrumbList, Product",
    height=120,
    key="detected_text"
)

detected_terms = parse_detected_schemas(detected_text)

base_df = all_df[all_df["month"] == selected_month].copy()
df = enrich(base_df, selected_niche, detected_terms)

if niche_mode == "Customize niche":
    df["in_niche_playbook"] = df["term"].apply(
        lambda term: term in active_playbook_terms
    )

    df["niche_relevant"] = df["term"].apply(
        lambda term: term in active_playbook_terms
    )

    df["priority_score"] = (
        df["adoption_tier"] * 8
        + df["seo_value"] * 8
        + df["google_status"].apply(status_points)
        + df["niche_relevant"].astype(int) * 15
        + df["in_niche_playbook"].astype(int) * 15
        - df["cms_bias"].apply(bias_penalty)
    ).clip(lower=0, upper=100).round(0).astype(int)

    df["priority"] = df["priority_score"].apply(priority_label)
    df["recommendation_bucket"] = df.apply(classify_opportunity, axis=1)

playbook_terms = active_playbook_terms
playbook_df = df[df["term"].isin(playbook_terms)].copy()

# Include knowledge-layer terms even if the usage dataset does not contain them.
missing_from_usage = [t for t in playbook_terms if t not in playbook_df["term"].tolist()]
if missing_from_usage:
    additions = []
    for term in missing_from_usage:
        additions.append({
            "month": selected_month,
            "term_type": "Type",
            "term": term,
            "bucket": "Not in dataset",
            "adoption_tier": 0,
            "estimated_domains_midpoint": 0,
        })
    additions_df = enrich(pd.DataFrame(additions), selected_niche, detected_terms)
    playbook_df = pd.concat([playbook_df, additions_df], ignore_index=True)

playbook_df = playbook_df.sort_values("priority_score", ascending=False)

with st.sidebar.expander("Dataset health"):
    st.write("Rows loaded:", len(df))
    st.write("CSV files found:", len(csv_files))
    st.write("Months available:", len(months))
    st.write("Skipped files:", len(skipped_files))
    st.write("Detected schemas parsed:", detected_terms)

# =========================================================
# TOP KPIS
# =========================================================

expected_count = len(playbook_terms)
detected_in_playbook = int(playbook_df["site_status"].eq("Detected").sum())
missing_in_playbook = expected_count - detected_in_playbook
coverage = round((detected_in_playbook / expected_count) * 100, 1) if expected_count else 0

k1, k2, k3, k4 = st.columns(4)
k1.metric("Niche playbook schemas", expected_count)
k2.metric("Detected in your list", detected_in_playbook)
k3.metric("Missing from your list", missing_in_playbook)
k4.metric("Playbook coverage", f"{coverage}%")

tabs = st.tabs([
    "Niche Playbook",
    "Priority Roadmap",
    "Gap Analysis",
    "Compare Top Schemas",
    "Adoption vs Google",
    "Trend Watch",
    "Export Report",
    "Guide & Credits"
])

# =========================================================
# TAB 1 NICHE PLAYBOOK
# =========================================================

with tabs[0]:
    f"{active_niche} Schema Playbook"

    st.markdown(
        "This is the recommended schema set for the selected niche, ranked by SEO priority."
    )

    st.dataframe(
        playbook_df[
            [
                "term", "site_status", "priority", "priority_score",
                "recommendation_bucket", "bucket", "adoption_tier",
                "google_feature", "google_status", "cms_bias",
                "why_it_matters", "audit_focus"
            ]
        ],
        use_container_width=True
    )

    fig = px.bar(
        playbook_df.sort_values("priority_score", ascending=False),
        x="term",
        y="priority_score",
        color="recommendation_bucket",
        hover_data=["bucket", "google_status", "google_feature", "site_status", "cms_bias"],
        title=f"Schema Priority Score — {f"{active_niche} Schema Playbook"}",
        labels={"term": "Schema", "priority_score": "Priority Score"}
    )
    st.plotly_chart(fig, use_container_width=True)

# =========================================================
# TAB 2 ROADMAP
# =========================================================

with tabs[1]:
    st.header("Priority Roadmap")

    col1, col2 = st.columns(2)

    with col1:
        st.subheader("Implement next")
        implement_df = playbook_df[
            (playbook_df["site_status"] == "Missing")
            & (playbook_df["recommendation_bucket"].isin(["Hidden gap", "Core missing schema"]))
        ].sort_values("priority_score", ascending=False)

        if implement_df.empty:
            st.success("No critical missing schemas found in the current playbook.")
        else:
            st.dataframe(
                implement_df[
                    ["term", "priority", "priority_score", "bucket", "google_feature", "google_status", "audit_focus"]
                ],
                use_container_width=True
            )

    with col2:
        st.subheader("Audit quality")
        audit_df = playbook_df[
            playbook_df["site_status"] == "Detected"
        ].sort_values("priority_score", ascending=False)

        if audit_df.empty:
            st.info("Paste detected schemas in the sidebar to populate this section.")
        else:
            st.dataframe(
                audit_df[
                    ["term", "priority", "priority_score", "bucket", "google_feature", "google_status", "audit_focus"]
                ],
                use_container_width=True
            )

    st.subheader("Use cautiously")
    caution_df = playbook_df[playbook_df["recommendation_bucket"] == "Use cautiously"].copy()
    st.dataframe(
        caution_df[
            ["term", "site_status", "priority", "priority_score", "google_feature", "google_status", "why_it_matters"]
        ],
        use_container_width=True
    )

# =========================================================
# TAB 3 GAP ANALYSIS
# =========================================================

with tabs[2]:
    st.header("Gap Analysis")

    gap_counts = (
        playbook_df.groupby(["recommendation_bucket", "site_status"])
        .size()
        .reset_index(name="count")
        .sort_values("count", ascending=False)
    )

    fig_gap = px.bar(
        gap_counts,
        x="recommendation_bucket",
        y="count",
        color="site_status",
        title="Gap Buckets by Site Status",
        labels={"recommendation_bucket": "Gap Bucket", "count": "Schemas"}
    )
    st.plotly_chart(fig_gap, use_container_width=True)

    selected_bucket = st.selectbox(
        "Inspect a bucket",
        sorted(playbook_df["recommendation_bucket"].unique()),
        key="inspect_bucket"
    )

    bucket_df = playbook_df[playbook_df["recommendation_bucket"] == selected_bucket].copy()

    st.dataframe(
        bucket_df[
            [
                "term", "site_status", "priority", "priority_score",
                "bucket", "google_feature", "google_status",
                "cms_bias", "why_it_matters", "audit_focus"
            ]
        ].sort_values("priority_score", ascending=False),
        use_container_width=True
    )

# =========================================================
# TAB 4 COMPARE TOP SCHEMAS
# =========================================================

with tabs[3]:
    st.header("Compare Top Schemas")

    st.markdown(
        "Select up to 6 schemas from the niche playbook or the full dataset."
    )

    selection_source = st.radio(
        "Selection source",
        ["Niche playbook", "Full Schema.org dataset"],
        horizontal=True,
        key="selection_source"
    )

    if selection_source == "Niche playbook":
        options = playbook_df["term"].dropna().tolist()
        default_selection = playbook_df.sort_values("priority_score", ascending=False)["term"].head(min(6, len(playbook_df))).tolist()
    else:
        options = sorted(df["term"].dropna().unique())
        default_selection = []
    
    selected_compare = st.multiselect(
        "Choose up to 6 schemas",
        options=options,
        default=[x for x in default_selection if x in options],
        max_selections=6,
        key="compare_schema_selector"
    )

    if not selected_compare:
        st.warning("Choose at least one schema to compare.")
    else:
        compare_df = df[df["term"].isin(selected_compare)].copy()

        # If a selected playbook term is absent from the usage dataset, add placeholder.
        absent = [t for t in selected_compare if t not in compare_df["term"].tolist()]
        if absent:
            additions = pd.DataFrame([
                {
                    "month": selected_month,
                    "term_type": "Type",
                    "term": t,
                    "bucket": "Not in dataset",
                    "adoption_tier": 0,
                    "estimated_domains_midpoint": 0,
                }
                for t in absent
            ])
            compare_df = pd.concat([compare_df, additions], ignore_index=True)

        compare_df = enrich(compare_df, selected_niche, detected_terms)
        compare_df["order"] = compare_df["term"].apply(lambda t: selected_compare.index(t))
        compare_df = compare_df.sort_values("order")

        fig_compare = px.bar(
            compare_df.sort_values("priority_score", ascending=False),
            x="term",
            y="priority_score",
            color="recommendation_bucket",
            hover_data=["bucket", "adoption_tier", "google_status", "google_feature", "cms_bias", "site_status"],
            title="Schema Comparison by Priority Score",
            labels={"term": "Schema", "priority_score": "Priority Score"}
        )
        st.plotly_chart(fig_compare, use_container_width=True)

        st.dataframe(
            compare_df[
                [
                    "term", "site_status", "priority", "priority_score",
                    "recommendation_bucket", "bucket", "adoption_tier",
                    "google_feature", "google_status", "cms_bias",
                    "why_it_matters", "audit_focus"
                ]
            ].sort_values("priority_score", ascending=False),
            use_container_width=True
        )

# =========================================================
# TAB 5 ADOPTION VS GOOGLE
# =========================================================

with tabs[4]:
    st.header("Adoption vs Google Documentation")

    st.markdown(
        "This view separates popular schemas from schemas that are actually mapped to Google-documented structured data features."
    )

    full_types = df.copy()

    available_buckets = sorted(
        full_types["recommendation_bucket"]
        .dropna()
        .astype(str)
        .unique()
        .tolist()
    )

    if not available_buckets:
        st.warning("No recommendation buckets available for this dataset/month.")
        st.dataframe(full_types.head(50), use_container_width=True)
    else:
        lens_filter = st.multiselect(
            "Filter recommendation buckets",
            options=available_buckets,
            default=available_buckets,
            key="lens_filter"
        )

        lens_df = full_types[
            full_types["recommendation_bucket"].astype(str).isin(lens_filter)
        ].copy()

        fig_lens = px.scatter(
            lens_df,
            x="adoption_tier",
            y="priority_score",
            color="recommendation_bucket",
            size="seo_value",
            hover_name="term",
            hover_data=[
                "bucket",
                "google_feature",
                "google_status",
                "niche_relevant",
                "cms_bias",
            ],
            title="Public Adoption vs Niche SEO Priority",
            labels={
                "adoption_tier": "Adoption Tier",
                "priority_score": "Priority Score",
            }
        )

        st.plotly_chart(fig_lens, use_container_width=True)

        st.dataframe(
            lens_df[
                [
                    "term",
                    "recommendation_bucket",
                    "priority",
                    "priority_score",
                    "bucket",
                    "adoption_tier",
                    "google_feature",
                    "google_status",
                    "niche_relevant",
                    "cms_bias",
                    "why_it_matters",
                ]
            ].sort_values("priority_score", ascending=False).head(100),
            use_container_width=True
        )

# =========================================================
# TAB 6 TREND WATCH
# =========================================================

with tabs[5]:
    st.header("Trend Watch")

    trend_options = playbook_df["term"].tolist()

    selected_trend_terms = st.multiselect(
        "Choose playbook schemas to trend",
        options=trend_options,
        default=trend_options[:min(5, len(trend_options))],
        max_selections=6,
        key="trend_terms"
    )

    if not selected_trend_terms:
        st.warning("Choose at least one schema.")
    else:
        trend_df = all_df[all_df["term"].isin(selected_trend_terms)].copy()
        trend_df = enrich(trend_df, selected_niche, detected_terms)

        fig_trend = px.line(
            trend_df.sort_values("month"),
            x="month",
            y="adoption_tier",
            color="term",
            markers=True,
            title="Adoption Tier Trend",
            labels={"month": "Month", "adoption_tier": "Adoption Tier"}
        )
        st.plotly_chart(fig_trend, use_container_width=True)

        pivot = trend_df.pivot_table(
            index="month",
            columns="term",
            values="bucket",
            aggfunc="first"
        ).reset_index()

        st.dataframe(pivot, use_container_width=True)

# =========================================================
# TAB 7 EXPORT
# =========================================================

with tabs[6]:
    st.header("Export Report")

    report_df = playbook_df.sort_values("priority_score", ascending=False).copy()

    st.dataframe(
        report_df[
            [
                "term", "site_status", "priority", "priority_score",
                "recommendation_bucket", "bucket", "adoption_tier",
                "google_feature", "google_status", "cms_bias",
                "why_it_matters", "audit_focus"
            ]
        ],
        use_container_width=True
    )

    csv = report_df.to_csv(index=False).encode("utf-8")
    st.download_button(
        "Download CSV playbook",
        data=csv,
        file_name=f"schema_niche_playbook_{active_niche}_{selected_month}.csv",
        mime="text/csv"
    )

    markdown = [
        "# What Schemas Should I Care About for My Niche?",
        "",
        f"Generated: {datetime.utcnow().strftime('%Y-%m-%d')}",
        f"Niche: {active_niche}",
        f"Dataset month: {selected_month}",
        "",
        "## Executive Summary",
        "",
        f"- Playbook schemas: {expected_count}",
        f"- Detected in provided list: {detected_in_playbook}",
        f"- Missing from provided list: {missing_in_playbook}",
        f"- Coverage: {coverage}%",
        "",
        "## Recommendations",
        "",
    ]

    for _, row in report_df.iterrows():
        markdown.append(make_recommendation(row, active_niche))
        markdown.append("")

    markdown_text = "\n".join(markdown)

    st.text_area("Markdown report", markdown_text, height=420)

    st.download_button(
        "Download Markdown report",
        data=markdown_text.encode("utf-8"),
        file_name=f"schema_niche_playbook_{selected_niche}_{selected_month}.md",
        mime="text/markdown"
    )

# =========================================================
# TAB 8 GUIDE & CREDITS
# =========================================================

with tabs[7]:
    st.header("Guide & Methodology")

    st.markdown(
        """
This guide explains how the app works, how the metrics are calculated, and how SEO professionals should interpret the results.

The goal of this tool is not to say that a schema type is “better” only because it is popular.

The main question is:

> **What schemas should I care about for this specific niche?**
"""
    )

    st.subheader("1. Data Source")

    st.markdown(
        """
The adoption data comes from the **Schema.org Public Usage Statistics** dataset.

The dataset provides monthly aggregated usage statistics for Schema.org terms across many domains.

The app uses three core columns from the dataset:

| Column | Meaning |
|---|---|
| `Class` | Whether the term is a Type or Property |
| `Name` | The Schema.org term name |
| `Domain Bucket` | Estimated bucket of unique domains using the term |

Important: the dataset uses buckets, not exact counts.
"""
    )

    st.subheader("2. Adoption Tier")

    st.markdown(
        """
The app converts each `Domain Bucket` into an ordinal adoption tier.

| Domain Bucket | Adoption Tier |
|---|---:|
| `< 1K` | 1 |
| `1K - 10K` | 2 |
| `10K - 100K` | 3 |
| `100K - 1M` | 4 |
| `> 1M` | 5 |

This does **not** mean exact popularity.

It only means the term appears within a broader adoption range.
"""
    )

    st.code(
        """
BUCKET_ORDER = {
    "< 1K": 1,
    "1K - 10K": 2,
    "10K - 100K": 3,
    "100K - 1M": 4,
    "> 1M": 5,
}
""",
        language="python"
    )

    st.subheader("3. Google Rich Result Layer")

    st.markdown(
        """
The app includes an editable knowledge layer that maps selected Schema.org terms to Google Search structured data features.

Examples:

| Schema | Google Feature | Status |
|---|---|---|
| Product | Product snippets / Merchant listings | Documented rich result |
| BreadcrumbList | Breadcrumb | Documented rich result |
| VideoObject | Video | Documented rich result |
| FAQPage | FAQ | Limited / reduced visibility |
| TVSeries | Entity understanding | Not a standalone rich result |

Important:

> Google documentation indicates eligibility for a rich result, not a guarantee that the rich result will appear.
"""
    )

    st.subheader("4. Niche Playbook")

    st.markdown(
        """
Each niche has a recommended schema playbook.

For example:

**Ecommerce**

- Product
- Offer
- AggregateRating
- Review
- BreadcrumbList
- Organization
- VideoObject
- FAQPage

**Entertainment**

- Movie
- VideoObject
- TVSeries
- TVSeason
- TVEpisode
- Review
- AggregateRating
- BreadcrumbList

The app now supports two modes:

| Mode | Description |
|---|---|
| Use preset niche | Uses the predefined playbook |
| Customize niche | Lets the user select their own schema terms |
"""
    )

    st.subheader("5. Priority Score")

    st.markdown(
        """
The `priority_score` is a heuristic score from 0 to 100.

It combines:

1. Public adoption
2. SEO value
3. Google documentation status
4. Niche relevance
5. Inclusion in the niche playbook
6. CMS/plugin-default bias

Current formula:
"""
    )

    st.code(
        """
priority_score = (
    adoption_tier * 8
    + seo_value * 8
    + google_status_points
    + niche_relevant * 15
    + in_niche_playbook * 15
    - cms_bias_penalty
)
""",
        language="python"
    )

    st.markdown(
        """
Then the score is clipped between 0 and 100.

| Signal | Effect |
|---|---|
| Higher adoption tier | Increases score |
| Higher SEO value | Increases score |
| Google-documented rich result | Increases score |
| Relevant to selected niche | Increases score |
| Included in niche playbook | Increases score |
| High CMS/plugin bias | Decreases score |

The score is not a ranking factor.  
It is an **audit prioritization score**.
"""
    )

    st.subheader("6. Priority Labels")

    st.markdown(
        """
The app converts the numeric score into a practical priority label.

| Priority Score | Label |
|---:|---|
| 80 - 100 | Critical |
| 60 - 79 | High |
| 40 - 59 | Medium |
| 0 - 39 | Low |
"""
    )

    st.subheader("7. Recommendation Buckets")

    st.markdown(
        """
The app also classifies each schema into a recommendation bucket.

| Bucket | Meaning |
|---|---|
| Core missing schema | Strong niche fit, documented by Google, and missing from detected schemas |
| Hidden gap | Google-documented and niche-relevant, but not broadly adopted |
| Audit quality | Already detected; focus on quality and validation |
| Semantic opportunity | Useful for entity architecture, but not a direct rich-result target |
| Use cautiously | Limited or reduced Google visibility |
| Popular / plugin-driven | Common because CMSs/plugins often generate it |
| Low priority | Not clearly useful for the selected niche |
"""
    )

    st.subheader("8. How to Use Each Feature")

    st.markdown(
        """
### Niche Playbook

Shows the recommended schema set for the selected niche.

Use it to answer:

> “Which schemas matter most for this kind of site?”

---

### Priority Roadmap

Splits schemas into implementation actions.

Use it to answer:

> “What should we implement next?”

---

### Gap Analysis

Compares the niche playbook against schemas already detected on the site.

Use it to answer:

> “What is missing from our structured data implementation?”

---

### Compare Top Schemas

Lets you compare up to 6 schemas side by side.

Use it to answer:

> “Should I prioritize Product, VideoObject, FAQPage, Review, or something else?”

---

### Adoption vs Google

Separates public-web adoption from Google-documented Search features.

Use it to answer:

> “Is this schema popular, actually useful for rich results, or just plugin noise?”

---

### Trend Watch

Shows monthly adoption-tier movement.

Use it to answer:

> “Is this schema becoming more common over time?”

---

### Export Report

Exports CSV and Markdown reports for audits, clients, stakeholders, or internal SEO roadmaps.
"""
    )

    st.subheader("9. Interpretation Rules")

    st.markdown(
        """
Use the results carefully:

- High adoption does not always mean high SEO impact.
- Low adoption does not always mean low value.
- Google-documented eligibility does not guarantee rich-result visibility.
- Plugin-generated schemas can inflate adoption numbers.
- The best schema priority depends on page templates, visible content, and business model.
- Always validate implementation with Google’s Rich Results Test and Search Console where applicable.
"""
    )

    st.subheader("10. Credits")

    st.markdown(
        """
Created by **Daniel Amaral**.

LinkedIn: [Daniel Amaral](https://www.linkedin.com/in/danielamaralrocha/)

Concept, SEO methodology, and product direction by Daniel Rocha.

Data source: Schema.org Public Usage Statistics.  
Google feature mapping: editable SEO knowledge layer based on Google Search structured data documentation.
"""
    )

st.caption(
    "Data source: Schema.org Public Usage Statistics. Google mapping layer is editable and should be maintained against Google Search structured data documentation."
)


