import streamlit as st
import pandas as pd
import plotly.express as px
import requests
from io import StringIO

st.set_page_config(
    page_title="Schema Adoption Intelligence",
    page_icon="🧠",
    layout="wide"
)

GITHUB_API_URL = "https://api.github.com/repos/schemaorg/schemaorg/contents/data/public_stats/google?ref=main"
RAW_BASE_URL = "https://raw.githubusercontent.com/schemaorg/schemaorg/main/data/public_stats/google/"

FALLBACK_FILES = ["2026_05.csv"]

BUCKET_ORDER = {
    "< 1K": 1,
    "1K - 10K": 2,
    "10K - 100K": 3,
    "100K - 1M": 4,
    "> 1M": 5
}

SEO_KNOWLEDGE = {
    "Product": {
        "rich_result": "Supported",
        "plugin_bias": "High",
        "verticals": ["Ecommerce", "Marketplace"],
        "templates": ["Product Page"],
        "gsc_report": "Product snippets / Merchant listings",
        "note": "High priority for ecommerce. Adoption may be inflated by ecommerce platforms and SEO plugins."
    },
    "Offer": {
        "rich_result": "Supported",
        "plugin_bias": "Medium",
        "verticals": ["Ecommerce", "Marketplace"],
        "templates": ["Product Page"],
        "gsc_report": "Product snippets / Merchant listings",
        "note": "Important for price, availability, and commercial product data."
    },
    "AggregateRating": {
        "rich_result": "Supported",
        "plugin_bias": "Medium",
        "verticals": ["Ecommerce", "Local Business", "Entertainment", "Education"],
        "templates": ["Product Page", "Review Page", "Local Page"],
        "gsc_report": "Product snippets / Review snippets",
        "note": "Useful when ratings are real, visible, and compliant with Google guidelines."
    },
    "Review": {
        "rich_result": "Supported",
        "plugin_bias": "Medium",
        "verticals": ["Ecommerce", "Local Business", "Entertainment"],
        "templates": ["Product Page", "Review Page"],
        "gsc_report": "Review snippets",
        "note": "Should represent genuine reviews visible on the page."
    },
    "BreadcrumbList": {
        "rich_result": "Supported",
        "plugin_bias": "High",
        "verticals": ["Ecommerce", "Publisher", "Local Business", "SaaS", "Education", "Entertainment", "Healthcare"],
        "templates": ["All Templates"],
        "gsc_report": "Breadcrumbs",
        "note": "Very common because many CMSs and SEO plugins generate it automatically."
    },
    "Article": {
        "rich_result": "Supported",
        "plugin_bias": "High",
        "verticals": ["Publisher", "Education", "Healthcare"],
        "templates": ["Article Page", "Blog Post"],
        "gsc_report": "Article rich results",
        "note": "Core markup for publishers, blogs, and editorial content."
    },
    "NewsArticle": {
        "rich_result": "Supported",
        "plugin_bias": "Medium",
        "verticals": ["Publisher"],
        "templates": ["News Page"],
        "gsc_report": "Article rich results",
        "note": "Most relevant for news publishers."
    },
    "FAQPage": {
        "rich_result": "Limited",
        "plugin_bias": "High",
        "verticals": ["Ecommerce", "SaaS", "Education", "Healthcare"],
        "templates": ["FAQ Page", "Support Page"],
        "gsc_report": "Limited visibility",
        "note": "Historically overused. Useful semantically, but should not be treated as a major rich-result lever."
    },
    "HowTo": {
        "rich_result": "Limited",
        "plugin_bias": "Medium",
        "verticals": ["Publisher", "Education", "SaaS"],
        "templates": ["Guide Page"],
        "gsc_report": "Limited visibility",
        "note": "Useful for instructional content, but lower rich-result value than in the past."
    },
    "VideoObject": {
        "rich_result": "Supported",
        "plugin_bias": "Medium",
        "verticals": ["Publisher", "Education", "Entertainment", "SaaS"],
        "templates": ["Video Page", "Article Page"],
        "gsc_report": "Videos",
        "note": "High priority when video is a meaningful part of the page."
    },
    "LocalBusiness": {
        "rich_result": "Supported",
        "plugin_bias": "Medium",
        "verticals": ["Local Business", "Healthcare"],
        "templates": ["Location Page", "Homepage"],
        "gsc_report": "Local business / Merchant-related results",
        "note": "Important for local businesses and location landing pages."
    },
    "Organization": {
        "rich_result": "Supported",
        "plugin_bias": "High",
        "verticals": ["Ecommerce", "Publisher", "Local Business", "SaaS", "Education", "Healthcare"],
        "templates": ["Homepage", "About Page"],
        "gsc_report": "Organization / Logo",
        "note": "Very common and often generated by SEO plugins by default."
    },
    "Person": {
        "rich_result": "Not direct",
        "plugin_bias": "Medium",
        "verticals": ["Publisher", "Education", "Healthcare"],
        "templates": ["Author Page", "Bio Page"],
        "gsc_report": "No direct report",
        "note": "Useful for authors, experts, professionals, and entity-level clarity."
    },
    "Event": {
        "rich_result": "Supported",
        "plugin_bias": "Low",
        "verticals": ["Local Business", "Education", "Entertainment"],
        "templates": ["Event Page"],
        "gsc_report": "Events",
        "note": "Highly actionable when the site publishes real events."
    },
    "JobPosting": {
        "rich_result": "Supported",
        "plugin_bias": "Low",
        "verticals": ["SaaS", "Marketplace", "Education"],
        "templates": ["Job Page"],
        "gsc_report": "Job postings",
        "note": "Highly actionable for job listing pages."
    },
    "Course": {
        "rich_result": "Supported",
        "plugin_bias": "Low",
        "verticals": ["Education"],
        "templates": ["Course Page"],
        "gsc_report": "Course info",
        "note": "High priority for education websites and course catalogs."
    },
    "Recipe": {
        "rich_result": "Supported",
        "plugin_bias": "Medium",
        "verticals": ["Publisher"],
        "templates": ["Recipe Page"],
        "gsc_report": "Recipes",
        "note": "Very relevant for recipe publishers."
    },
    "Dataset": {
        "rich_result": "Supported",
        "plugin_bias": "Low",
        "verticals": ["Education", "SaaS", "Publisher"],
        "templates": ["Dataset Page"],
        "gsc_report": "Dataset search",
        "note": "Useful for public datasets, research, and indexable data collections."
    },
    "TVSeries": {
        "rich_result": "Not direct",
        "plugin_bias": "Low",
        "verticals": ["Entertainment"],
        "templates": ["Series Page"],
        "gsc_report": "No direct report",
        "note": "Useful for semantic architecture in entertainment sites."
    },
    "TVSeason": {
        "rich_result": "Not direct",
        "plugin_bias": "Low",
        "verticals": ["Entertainment"],
        "templates": ["Season Page"],
        "gsc_report": "No direct report",
        "note": "Useful when there are dedicated season pages."
    },
    "TVEpisode": {
        "rich_result": "Not direct",
        "plugin_bias": "Low",
        "verticals": ["Entertainment"],
        "templates": ["Episode Page"],
        "gsc_report": "No direct report",
        "note": "Useful for episode-level pages and content catalogs."
    },
    "Movie": {
        "rich_result": "Supported",
        "plugin_bias": "Low",
        "verticals": ["Entertainment"],
        "templates": ["Movie Page"],
        "gsc_report": "Movie-related rich results",
        "note": "Important for movie catalogs and entertainment databases."
    },
    "SoftwareApplication": {
        "rich_result": "Supported",
        "plugin_bias": "Low",
        "verticals": ["SaaS"],
        "templates": ["Product Page", "App Page"],
        "gsc_report": "Software app rich results",
        "note": "Useful for software, SaaS, apps, and tool directories."
    }
}

VERTICAL_TEMPLATES = {
    "Ecommerce": ["Product", "Offer", "AggregateRating", "Review", "BreadcrumbList", "Organization", "FAQPage"],
    "Marketplace": ["Product", "Offer", "AggregateRating", "Review", "Organization", "BreadcrumbList"],
    "Publisher": ["Article", "NewsArticle", "Person", "Organization", "BreadcrumbList", "VideoObject", "FAQPage"],
    "Local Business": ["LocalBusiness", "Organization", "Review", "AggregateRating", "BreadcrumbList", "Event"],
    "SaaS": ["SoftwareApplication", "Organization", "Product", "FAQPage", "HowTo", "VideoObject", "BreadcrumbList"],
    "Education": ["Course", "Article", "Person", "Organization", "FAQPage", "VideoObject", "Dataset", "BreadcrumbList"],
    "Healthcare": ["LocalBusiness", "Person", "Article", "FAQPage", "BreadcrumbList", "Organization"],
    "Entertainment": ["TVSeries", "TVSeason", "TVEpisode", "Movie", "VideoObject", "Review", "AggregateRating", "BreadcrumbList"]
}


def normalize_bucket(value):
    value = str(value).strip()

    replacements = {
        "0-1K": "< 1K",
        "0 - 1K": "< 1K",
        "<1K": "< 1K",
        "< 1k": "< 1K",
        "1k-10k": "1K - 10K",
        "1K-10K": "1K - 10K",
        "10K-100K": "10K - 100K",
        "100K-1M": "100K - 1M",
        "1M+": "> 1M",
        ">1M": "> 1M"
    }

    return replacements.get(value, value)


def rich_result_points(status):
    if status == "Supported":
        return 30
    if status == "Limited":
        return 15
    if status == "Not direct":
        return 5
    return 0


def plugin_bias_penalty(status):
    if status == "High":
        return 15
    if status == "Medium":
        return 8
    if status == "Low":
        return 0
    return 3


def list_csv_files():
    try:
        response = requests.get(GITHUB_API_URL, timeout=20)

        if response.status_code != 200:
            return FALLBACK_FILES

        files = response.json()

        csv_files = [
            item["name"]
            for item in files
            if item["name"].endswith(".csv")
        ]

        csv_files = sorted(csv_files)

        if not csv_files:
            return FALLBACK_FILES

        return csv_files

    except Exception:
        return FALLBACK_FILES


@st.cache_data(ttl=3600)
def load_single_month(file_name):
    url = RAW_BASE_URL + file_name
    response = requests.get(url, timeout=30)

    if response.status_code != 200:
        raise Exception(f"Could not download {file_name}")

    df = pd.read_csv(StringIO(response.text))

    required_columns = ["Class", "Name", "Domain Bucket"]
    missing = [col for col in required_columns if col not in df.columns]

    if missing:
        raise Exception(f"Missing columns in {file_name}: {missing}")

    df["month"] = file_name.replace(".csv", "")
    df["term_type"] = df["Class"]
    df["term"] = df["Name"]
    df["bucket"] = df["Domain Bucket"].apply(normalize_bucket)
    df["adoption_tier"] = df["bucket"].map(BUCKET_ORDER).fillna(0).astype(int)

    return df


@st.cache_data(ttl=3600)
def load_all_months():
    files = list_csv_files()
    dataframes = []

    for file_name in files:
        try:
            dataframes.append(load_single_month(file_name))
        except Exception:
            pass

    if not dataframes:
        st.error("Could not load any Schema.org public usage statistics CSV.")
        st.stop()

    all_df = pd.concat(dataframes, ignore_index=True)
    return all_df, files


def enrich_with_seo_layer(df, selected_industry):
    df = df.copy()

    df["rich_result"] = df["term"].apply(
        lambda x: SEO_KNOWLEDGE.get(x, {}).get("rich_result", "Unknown")
    )

    df["plugin_bias"] = df["term"].apply(
        lambda x: SEO_KNOWLEDGE.get(x, {}).get("plugin_bias", "Unknown")
    )

    df["gsc_report"] = df["term"].apply(
        lambda x: SEO_KNOWLEDGE.get(x, {}).get("gsc_report", "Unknown")
    )

    df["seo_note"] = df["term"].apply(
        lambda x: SEO_KNOWLEDGE.get(x, {}).get("note", "No manual SEO annotation yet.")
    )

    df["industry_match"] = df["term"].apply(
        lambda x: selected_industry in SEO_KNOWLEDGE.get(x, {}).get("verticals", [])
    )

    df["expected_for_industry"] = df["term"].apply(
        lambda x: x in VERTICAL_TEMPLATES.get(selected_industry, [])
    )

    df["seo_actionability_score"] = (
        df["adoption_tier"] * 10
        + df["rich_result"].apply(rich_result_points)
        + df["industry_match"].astype(int) * 20
        + df["expected_for_industry"].astype(int) * 15
        - df["plugin_bias"].apply(plugin_bias_penalty)
    )

    df["seo_actionability_score"] = df["seo_actionability_score"].clip(lower=0, upper=100)

    def classify(row):
        score = row["seo_actionability_score"]

        if score >= 75:
            return "Critical"
        if score >= 55:
            return "High"
        if score >= 35:
            return "Medium"
        return "Low"

    df["seo_priority"] = df.apply(classify, axis=1)

    return df


def generate_recommendation(row, selected_industry):
    term = row["term"]
    tier = row["adoption_tier"]
    bucket = row["bucket"]
    rich = row["rich_result"]
    bias = row["plugin_bias"]
    priority = row["seo_priority"]
    score = int(row["seo_actionability_score"])
    note = row["seo_note"]

    text = f"""
### Executive Summary: `{term}`

**Public adoption:** Tier {tier} — {bucket}  
**Google rich result status:** {rich}  
**CMS/plugin default bias:** {bias}  
**SEO priority for {selected_industry}:** {priority}  
**SEO Actionability Score:** {score}/100

**Interpretation:**  
{note}

"""

    if rich == "Supported" and priority in ["Critical", "High"]:
        text += """
**Recommended action:**  
Audit the relevant page templates immediately. Validate whether the markup is present, complete, visible to users, and aligned with Google structured data guidelines.
"""
    elif rich == "Limited":
        text += """
**Recommended action:**  
Use carefully. This may still provide semantic value, but it should not be sold internally as a major rich-result growth lever.
"""
    elif rich == "Not direct":
        text += """
**Recommended action:**  
Use when it improves entity clarity, content architecture, or catalog structure. Do not prioritize it solely because of expected rich-result impact.
"""
    else:
        text += """
**Recommended action:**  
Investigate business relevance before implementation. Lack of explicit rich-result support does not automatically mean lack of semantic value.
"""

    return text


all_df, csv_files = load_all_months()

latest_month = sorted(all_df["month"].unique())[-1]

st.title("🧠 Schema Adoption Intelligence")

st.markdown(
    """
**Turn Schema.org adoption data into SEO decisions.**

Move beyond popularity and prioritize structured data that matters:
real-world adoption, rich-result eligibility, template coverage, and implementation bias.
"""
)

st.sidebar.header("Settings")

selected_industry = st.sidebar.selectbox(
    "Industry / Site Type",
    list(VERTICAL_TEMPLATES.keys()),
    index=list(VERTICAL_TEMPLATES.keys()).index("Ecommerce")
)

selected_month = st.sidebar.selectbox(
    "Dataset Month",
    sorted(all_df["month"].unique(), reverse=True),
    index=0
)

current_df = all_df[all_df["month"] == selected_month].copy()
current_df = enrich_with_seo_layer(current_df, selected_industry)

tabs = st.tabs(
    [
        "1. Adoption Explorer",
        "2. SEO Priority Matrix",
        "3. Template Coverage Audit",
        "4. Opportunity Discovery",
        "5. Trend Intelligence",
        "6. Industry Benchmark",
        "7. Action Recommendations"
    ]
)

with tabs[0]:
    st.header("Adoption Explorer")

    col1, col2, col3 = st.columns(3)

    with col1:
        term_type_filter = st.multiselect(
            "Term Type",
            sorted(current_df["term_type"].unique()),
            default=sorted(current_df["term_type"].unique())
        )

    with col2:
        bucket_filter = st.multiselect(
            "Adoption Bucket",
            list(BUCKET_ORDER.keys()),
            default=list(BUCKET_ORDER.keys())
        )

    with col3:
        search = st.text_input("Search Schema.org term", "TVSeries")

    explorer_df = current_df[
        current_df["term_type"].isin(term_type_filter)
        & current_df["bucket"].isin(bucket_filter)
    ]

    if search:
        explorer_df = explorer_df[
            explorer_df["term"].str.contains(search, case=False, na=False)
        ]

    st.dataframe(
        explorer_df[
            [
                "term",
                "term_type",
                "bucket",
                "adoption_tier",
                "rich_result",
                "plugin_bias",
                "seo_priority",
                "seo_actionability_score"
            ]
        ].sort_values("seo_actionability_score", ascending=False),
        use_container_width=True
    )

with tabs[1]:
    st.header("SEO Priority Matrix")

    matrix_df = current_df[current_df["term_type"] == "Type"].copy()

    fig = px.scatter(
        matrix_df,
        x="adoption_tier",
        y="seo_actionability_score",
        color="rich_result",
        size="seo_actionability_score",
        hover_name="term",
        hover_data=["bucket", "plugin_bias", "seo_priority"],
        title=f"Adoption Tier vs SEO Actionability Score — {selected_industry}",
        labels={
            "adoption_tier": "Adoption Tier",
            "seo_actionability_score": "SEO Actionability Score"
        }
    )

    st.plotly_chart(fig, use_container_width=True)

    st.subheader("Top SEO Priorities")

    st.dataframe(
        matrix_df[
            [
                "term",
                "bucket",
                "adoption_tier",
                "rich_result",
                "plugin_bias",
                "gsc_report",
                "seo_priority",
                "seo_actionability_score"
            ]
        ].sort_values("seo_actionability_score", ascending=False).head(50),
        use_container_width=True
    )

with tabs[2]:
    st.header("Template Coverage Audit")

    expected_terms = VERTICAL_TEMPLATES.get(selected_industry, [])

    audit_df = current_df[current_df["term"].isin(expected_terms)].copy()
    found_terms = set(audit_df["term"])
    missing_terms = [term for term in expected_terms if term not in found_terms]

    st.subheader(f"Expected Schema Types for {selected_industry}")

    st.dataframe(
        audit_df[
            [
                "term",
                "bucket",
                "adoption_tier",
                "rich_result",
                "gsc_report",
                "seo_priority",
                "seo_actionability_score",
                "seo_note"
            ]
        ].sort_values("seo_actionability_score", ascending=False),
        use_container_width=True
    )

    if missing_terms:
        st.warning("Some expected schema types were not found in the loaded dataset.")
        st.write(missing_terms)

    st.info(
        """
Use this section to move structured data discussions from generic schema ideas
to page-template auditing: homepage, product page, article page, category page,
author page, location page, event page, course page, video page, and more.
"""
    )

with tabs[3]:
    st.header("Opportunity Discovery")

    st.subheader("Hidden Opportunities")

    hidden_opportunities = current_df[
        (current_df["adoption_tier"] <= 3)
        & (current_df["rich_result"].isin(["Supported", "Limited"]))
        & (current_df["plugin_bias"].isin(["Low", "Medium"]))
    ].copy()

    st.caption("Low adoption, rich-result eligible or partially eligible, and not heavily driven by plugin defaults.")

    st.dataframe(
        hidden_opportunities[
            [
                "term",
                "bucket",
                "adoption_tier",
                "rich_result",
                "plugin_bias",
                "gsc_report",
                "seo_priority",
                "seo_actionability_score",
                "seo_note"
            ]
        ].sort_values("seo_actionability_score", ascending=False).head(50),
        use_container_width=True
    )

    st.subheader("Commodity Schemas")

    commodity_df = current_df[
        (current_df["adoption_tier"] >= 4)
        & (current_df["plugin_bias"].isin(["High", "Medium"]))
    ].copy()

    st.caption("High adoption and high CMS/plugin default bias. Useful, but not always a competitive advantage.")

    st.dataframe(
        commodity_df[
            [
                "term",
                "bucket",
                "adoption_tier",
                "rich_result",
                "plugin_bias",
                "seo_priority",
                "seo_actionability_score",
                "seo_note"
            ]
        ].sort_values(["plugin_bias", "adoption_tier"], ascending=False).head(50),
        use_container_width=True
    )

with tabs[4]:
    st.header("Trend Intelligence")

    term_options = sorted(all_df["term"].unique())

    default_term = "TVSeries" if "TVSeries" in term_options else term_options[0]

    term_for_trend = st.selectbox(
    "Choose a Schema.org term",
    term_options,
    index=term_options.index(default_term),
    key="trend_term_selectbox"
)

    trend_df = all_df[all_df["term"] == term_for_trend].copy()
    trend_df = trend_df.sort_values("month")

    fig_trend = px.line(
        trend_df,
        x="month",
        y="adoption_tier",
        markers=True,
        title=f"Adoption Trend — {term_for_trend}",
        labels={
            "month": "Month",
            "adoption_tier": "Adoption Tier"
        }
    )

    st.plotly_chart(fig_trend, use_container_width=True)

    st.dataframe(
        trend_df[
            [
                "month",
                "term",
                "term_type",
                "bucket",
                "adoption_tier"
            ]
        ],
        use_container_width=True
    )

    if len(trend_df) >= 2:
        first = trend_df.iloc[0]["adoption_tier"]
        last = trend_df.iloc[-1]["adoption_tier"]

        if last > first:
            st.success("Trend signal: adoption is growing.")
        elif last < first:
            st.warning("Trend signal: adoption is declining.")
        else:
            st.info("Trend signal: stable within the same adoption bucket.")

with tabs[5]:
    st.header("Industry Benchmark")

    expected_terms = VERTICAL_TEMPLATES.get(selected_industry, [])
    benchmark_df = current_df[current_df["term"].isin(expected_terms)].copy()

    expected_count = len(expected_terms)
    detected_count = benchmark_df["term"].nunique()
    coverage = round((detected_count / expected_count) * 100, 1) if expected_count else 0

    col1, col2, col3 = st.columns(3)

    col1.metric("Expected Schemas", expected_count)
    col2.metric("Detected in Dataset", detected_count)
    col3.metric("Benchmark Coverage", f"{coverage}%")

    st.subheader(f"{selected_industry} Benchmark Set")

    st.dataframe(
        benchmark_df[
            [
                "term",
                "bucket",
                "adoption_tier",
                "rich_result",
                "plugin_bias",
                "gsc_report",
                "seo_priority",
                "seo_actionability_score"
            ]
        ].sort_values("seo_actionability_score", ascending=False),
        use_container_width=True
    )

    fig_benchmark = px.bar(
        benchmark_df.sort_values("seo_actionability_score", ascending=False),
        x="term",
        y="seo_actionability_score",
        color="rich_result",
        title=f"SEO Actionability Benchmark — {selected_industry}",
        labels={
            "term": "Schema Type",
            "seo_actionability_score": "SEO Actionability Score"
        }
    )

    st.plotly_chart(fig_benchmark, use_container_width=True)

with tabs[6]:
    st.header("Action Recommendations")

    term_options = sorted(current_df["term"].unique())

    default_term = "Product" if "Product" in term_options else term_options[0]

    selected_term = st.selectbox(
    "Choose a Schema.org term",
    term_options,
    index=term_options.index(default_term),
    key="recommendation_term_selectbox"
)

    selected_rows = current_df[current_df["term"] == selected_term]

    if not selected_rows.empty:
        row = selected_rows.iloc[0]

        col1, col2, col3, col4 = st.columns(4)

        col1.metric("Adoption Tier", int(row["adoption_tier"]))
        col2.metric("Bucket", row["bucket"])
        col3.metric("Rich Result", row["rich_result"])
        col4.metric("SEO Score", int(row["seo_actionability_score"]))

        recommendation = generate_recommendation(row, selected_industry)
        st.markdown(recommendation)

        export_df = current_df[
            [
                "term",
                "term_type",
                "bucket",
                "adoption_tier",
                "rich_result",
                "plugin_bias",
                "gsc_report",
                "seo_priority",
                "seo_actionability_score",
                "seo_note"
            ]
        ].sort_values("seo_actionability_score", ascending=False)

        csv = export_df.to_csv(index=False).encode("utf-8")

        st.download_button(
            "Download SEO Intelligence CSV",
            data=csv,
            file_name=f"schema_intelligence_{selected_industry}_{selected_month}.csv",
            mime="text/csv"
        )

st.caption(
    "Adoption source: Schema.org Public Usage Statistics. SEO intelligence layer: manual prioritization model for technical SEO analysis."
)
